/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Hawk
 */
public class CartFrame extends javax.swing.JFrame {
User user;
String method;
    /**
     * Creates new form CartFrame
     */
    public CartFrame(User user) {
        this.user= user;
        initComponents();
        fetch();
         
        }
    public void fetch()
    {
        DatabaseConnection dbc;
         dbc= new DatabaseConnection();
         String query = "SELECT * FROM cart WHERE UserID = '"+user.getUserId()+"';";
         try
		{
			dbc.openConnection();
			dbc.result = dbc.st.executeQuery(query);
                        jTable1.setModel(DbUtils.resultSetToTableModel(dbc.result));
			dbc.closeConnection();
                        
		}
        catch(Exception e)
        {
            System.out.println(e.getMessage());
            
        
        }
       finally
         {
             int numOfRows= jTable1.getRowCount();
             int sum =0;
             for(int i=0;i<numOfRows;i++)
             {
                 sum = sum + Integer.parseInt(jTable1.getValueAt(i,3).toString()); //returns an instance( i.e object) of the type in that cell
             }
             tprice.setText(Integer.toString(sum));
         }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        tprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Confirm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PayPal = new javax.swing.JRadioButton();
        Bkash = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        itemRemove = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        imageadd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Home.setText("Back to Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home);
        Home.setBounds(10, 10, 110, 30);
        jPanel1.add(tprice);
        tprice.setBounds(180, 420, 130, 30);

        jLabel4.setText("Total Price: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 430, 70, 20);

        Confirm.setText("Confirm Order");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });
        jPanel1.add(Confirm);
        Confirm.setBounds(670, 480, 120, 30);

        jLabel3.setText("Address: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(610, 440, 70, 14);
        jPanel1.add(addressfield);
        addressfield.setBounds(670, 430, 180, 30);

        jLabel2.setText("Payment Options:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(460, 440, 130, 14);

        PayPal.setText("PayPal");
        PayPal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayPalActionPerformed(evt);
            }
        });
        jPanel1.add(PayPal);
        PayPal.setBounds(460, 490, 57, 23);

        Bkash.setText("Bkash");
        Bkash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkashActionPerformed(evt);
            }
        });
        jPanel1.add(Bkash);
        Bkash.setBounds(460, 460, 93, 23);

        jButton1.setText("Remove from Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 500, 140, 30);
        jPanel1.add(itemRemove);
        itemRemove.setBounds(180, 460, 130, 30);

        jLabel1.setText("Item to Remove: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 470, 100, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 0, 710, 402);
        jPanel1.add(imageadd);
        imageadd.setBounds(0, 0, 860, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DatabaseConnection dbc;
         dbc= new DatabaseConnection();
         
        
        
        
        String query = "DELETE FROM cart WHERE UserID='"+user.getUserId()+"' AND ProductName='"+itemRemove.getText()+"';";
		
		try
		{
			dbc.openConnection();
			dbc.st.executeUpdate(query);
			dbc.closeConnection();
		}
		catch(Exception ex)
                {
                    System.out.println(ex.getMessage());
                    
                }
                finally
                {
                fetch();
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
         DatabaseConnection dbc;
         dbc= new DatabaseConnection();
         
        
        
        
        String query = "UPDATE cart SET Address='"+addressfield.getText()+"', PaymentMethod = '"+method+"', ProductStatus = 'Processing' WHERE UserID='"+user.getUserId()+"'";
		
		try
		{
			dbc.openConnection();
			dbc.st.executeUpdate(query);
			dbc.closeConnection();
		}
		catch(Exception ex)
                {
                    System.out.println(ex.getMessage());
                }
                finally
                {
                    fetch();
                    JOptionPane.showMessageDialog(this, "Your orders are now pending. Please wait for confirmation!");
                }
                
                
        
    }//GEN-LAST:event_ConfirmActionPerformed

    private void BkashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkashActionPerformed
        // TODO add your handling code here:
        if(Bkash.isSelected())
        {
            method="Bkash";
            PayPal.setSelected(false);
        }
            
    }//GEN-LAST:event_BkashActionPerformed

    private void PayPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayPalActionPerformed
        // TODO add your handling code here:
         if(PayPal.isSelected())
        {
            method="Paypal";
            Bkash.setSelected(false);
        }
    }//GEN-LAST:event_PayPalActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        UserHome uh = new UserHome(user);
        uh.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bkash;
    private javax.swing.JButton Confirm;
    private javax.swing.JButton Home;
    private javax.swing.JRadioButton PayPal;
    private javax.swing.JTextField addressfield;
    private javax.swing.JLabel imageadd;
    private javax.swing.JTextField itemRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tprice;
    // End of variables declaration//GEN-END:variables
}
