
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hawk
 */
public class FindGame extends javax.swing.JFrame {
    User user;
    /**
     * Creates new form FindGame
     */
    public FindGame(User user) {
        this.user= user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        StartViewing = new javax.swing.JButton();
        LoadInfo = new javax.swing.JButton();
        enterGame = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        Home.setText("Back to Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel2.add(Home);
        Home.setBounds(20, 13, 130, 30);

        StartViewing.setText("View Now");
        StartViewing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartViewingActionPerformed(evt);
            }
        });
        jPanel2.add(StartViewing);
        StartViewing.setBounds(300, 300, 90, 30);

        LoadInfo.setText("Load Info");
        LoadInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadInfoActionPerformed(evt);
            }
        });
        jPanel2.add(LoadInfo);
        LoadInfo.setBounds(410, 300, 100, 30);
        jPanel2.add(enterGame);
        enterGame.setBounds(380, 240, 160, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Game :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(280, 240, 110, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7201.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 850, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadInfoActionPerformed
        // TODO add your handling code here:
         GameSto gt = new GameSto();
        Game game = gt.getGame(enterGame.getText());
        
        if(game!= null)
        {
            switch(game.getName())
            {
                case "Cyberpunk 2077":
                   gFrame1 f1 = new gFrame1(user);
                    f1.setVisible(true);
                    this.setVisible(false);
                    break;
                    
                case "Fallout 4" :
                    gFrame2 f2 = new gFrame2(user);
                    f2.setVisible(true);
                    this.setVisible(false);
                    break;
                    
                case "FIFA 20" :
                    gFrame3 f3 = new gFrame3(user);
                    f3.setVisible(true);
                    this.setVisible(false);
                    break;
                    
                case "Gears 5" :
                    gFrame4 f4 = new gFrame4(user);
                    f4.setVisible(true);
                    this.setVisible(false);
                    break;
                    
                case "Need For Speed: Heat" :
                    gFrame5 f5 = new gFrame5(user);
                    f5.setVisible(true);
                    this.setVisible(false);
                    break;
                    
                    
                case "Red Dead Redemption 2" :
                    gFrame6 f6 = new gFrame6(user);
                    f6.setVisible(true);
                    this.setVisible(false);
                    break;
                    
                    
                case "Star Wars Jedi: Fallen Order" :
                    gFrame7 f7 = new gFrame7(user);
                    f7.setVisible(true);
                    this.setVisible(false);
                    break;
                    
                    
                case "The Outer Worlds" :
                    gFrame8 f8 = new gFrame8(user);
                    f8.setVisible(true);
                    this.setVisible(false);
                    break;
                    
                    
                    
                case "The Witcher 3: Wild Hunt" :
                    gFrame9 f9 = new gFrame9(user);
                    f9.setVisible(true);
                    this.setVisible(false);
                    break;
                    
                case "Death Stranding" :
                    gFrame10 f10 = new gFrame10(user);
                    f10.setVisible(true);
                    this.setVisible(false);
                    break;
                    
                
                    
            }
        }
            
            else
            {
                    JOptionPane.showMessageDialog(this, " Enter a Valid Game");
            }
        
    }//GEN-LAST:event_LoadInfoActionPerformed

    private void StartViewingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartViewingActionPerformed
        // TODO add your handling code here:
                gFrame1 f1 = new gFrame1(user);
                f1.setVisible(true);
                this.setVisible(false);
                
                    
    }//GEN-LAST:event_StartViewingActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
            UserHome uh = new UserHome(user);
            uh.setVisible(true);
            this.setVisible(false);
        
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton LoadInfo;
    private javax.swing.JButton StartViewing;
    private javax.swing.JTextField enterGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
