
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hawk
 */
public class Orders extends javax.swing.JFrame {
User user;
    /**
     * Creates new form Orders
     */
    public Orders(User user) {
        initComponents();
        this.user= user;
        
    }
    public void fetchAll()
    {
        DatabaseConnection dbc;
         dbc= new DatabaseConnection();
         String query = "SELECT * FROM cart;";
         try
		{
			dbc.openConnection();
			dbc.result = dbc.st.executeQuery(query);
                        jTable2.setModel(DbUtils.resultSetToTableModel(dbc.result));
			dbc.closeConnection();
                        
		}
        catch(Exception e)
        {
            System.out.println(e.getMessage());
            
        
        }
        
        
    }
    public void fetchOne()
    {
        DatabaseConnection dbc;
         dbc= new DatabaseConnection();
         String query = "SELECT * FROM cart WHERE UserID = '"+idField.getText()+"';";
         try
		{
			dbc.openConnection();
			dbc.result = dbc.st.executeQuery(query);
                        jTable2.setModel(DbUtils.resultSetToTableModel(dbc.result));
			dbc.closeConnection();
                        
		}
        catch(Exception e)
        {
            System.out.println(e.getMessage());
            
            
        
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ViewAll = new javax.swing.JButton();
        viewOrder = new javax.swing.JButton();
        RejectOneOrder = new javax.swing.JButton();
        RejectAll = new javax.swing.JButton();
        AcceptOneOrder = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        AcceptAll = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        ViewAll.setText("View All");
        ViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllActionPerformed(evt);
            }
        });
        jPanel1.add(ViewAll);
        ViewAll.setBounds(540, 430, 100, 30);

        viewOrder.setText("View Order");
        viewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderActionPerformed(evt);
            }
        });
        jPanel1.add(viewOrder);
        viewOrder.setBounds(30, 200, 110, 30);

        RejectOneOrder.setText("Reject Order");
        RejectOneOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectOneOrderActionPerformed(evt);
            }
        });
        jPanel1.add(RejectOneOrder);
        RejectOneOrder.setBounds(30, 300, 110, 30);

        RejectAll.setText("Reject All");
        RejectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectAllActionPerformed(evt);
            }
        });
        jPanel1.add(RejectAll);
        RejectAll.setBounds(430, 430, 100, 30);

        AcceptOneOrder.setText("Accept Order");
        AcceptOneOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptOneOrderActionPerformed(evt);
            }
        });
        jPanel1.add(AcceptOneOrder);
        AcceptOneOrder.setBounds(30, 250, 110, 30);
        jPanel1.add(idField);
        idField.setBounds(100, 130, 110, 30);

        jLabel1.setText("UserID: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 140, 60, 14);

        AcceptAll.setText("Accept All Oders");
        AcceptAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptAllActionPerformed(evt);
            }
        });
        jPanel1.add(AcceptAll);
        AcceptAll.setBounds(280, 430, 120, 30);

        Home.setText("Back to Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home);
        Home.setBounds(10, 10, 120, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(270, 0, 580, 402);
        jPanel1.add(image);
        image.setBounds(0, 0, 850, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        EmployeeHome eh = new EmployeeHome(user);
        eh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeActionPerformed

    private void AcceptOneOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptOneOrderActionPerformed
        // TODO add your handling code here:
        DatabaseConnection dbc;
         dbc= new DatabaseConnection();
         String query2 = "UPDATE cart SET ProductStatus = 'Accepted' WHERE UserID='"+idField.getText()+"'";
         try
		{
			dbc.openConnection();
			dbc.st.executeUpdate(query2);
			dbc.closeConnection();
                        
		}
        catch(Exception e)
        {
            System.out.println(e.getMessage());
            
        
        }
         finally
         {
             fetchOne();
         }
    }//GEN-LAST:event_AcceptOneOrderActionPerformed

    private void viewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderActionPerformed
        // TODO add your handling code here:
        fetchOne();
    }//GEN-LAST:event_viewOrderActionPerformed

    private void ViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllActionPerformed
        // TODO add your handling code here:
        fetchAll();
    }//GEN-LAST:event_ViewAllActionPerformed

    private void RejectOneOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectOneOrderActionPerformed
        // TODO add your handling code here:
        DatabaseConnection dbc;
        dbc= new DatabaseConnection();
         
        
        
        
        String query = "DELETE FROM cart WHERE UserID='"+idField.getText()+"';";
		
		try
		{
			dbc.openConnection();
			dbc.st.executeUpdate(query);
			dbc.closeConnection();
		}
		catch(Exception ex)
                {
                    System.out.println(ex.getMessage());
                }
                finally
                {
                    fetchOne();
                }
        
    }//GEN-LAST:event_RejectOneOrderActionPerformed

    private void AcceptAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptAllActionPerformed
        // TODO add your handling code here:
        DatabaseConnection dbc;
         dbc= new DatabaseConnection();
         String query2 = "UPDATE cart SET ProductStatus = 'Accepted';";
         try
		{
			dbc.openConnection();
			dbc.st.executeUpdate(query2);
			dbc.closeConnection();
                        
		}
        catch(Exception e)
        {
            System.out.println(e.getMessage());
            
        
        }
         finally
         {
             fetchAll();
         }
    }//GEN-LAST:event_AcceptAllActionPerformed

    private void RejectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectAllActionPerformed
        // TODO add your handling code here:
        DatabaseConnection dbc;
         dbc= new DatabaseConnection();
         
           String query = "DELETE FROM cart;";
		
		try
		{
			dbc.openConnection();
			dbc.st.executeUpdate(query);
			dbc.closeConnection();
		}
		catch(Exception ex)
                {
                    System.out.println(ex.getMessage());
                }
                finally
                {
                    fetchAll();
                }
    }//GEN-LAST:event_RejectAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptAll;
    private javax.swing.JButton AcceptOneOrder;
    private javax.swing.JButton Home;
    private javax.swing.JButton RejectAll;
    private javax.swing.JButton RejectOneOrder;
    private javax.swing.JButton ViewAll;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton viewOrder;
    // End of variables declaration//GEN-END:variables
}
