/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import AppPackage.AnimationClass;
import javax.swing.ImageIcon;

/**
 *
 * @author ayshi
 */
public class slide extends javax.swing.JFrame {
AnimationClass ac=new AnimationClass();
    /**
     * Creates new form slide
     */
    public slide() {
        initComponents();
        slideshow();
    }
    
    public void slideshow()
    {
        new Thread()
        { int count;
        @Override
        public void run()
        {
        try
        {
        while(true)
        {
        switch(count)
        {
            case 0:
               
               
                
                Thread.sleep(3000);
                ac.jLabelXLeft(0, -840, 20, 7, jLabel1);
                ac.jLabelXLeft(840, 0, 20, 7, jLabel2);
                
                count=1;
               
                break;
                
                
                case 1:
                     
                
                Thread.sleep(3000);
                ac.jLabelXRight(-840, 0, 20, 7, jLabel1);
                ac.jLabelXRight(0, 840, 20, 7, jLabel2);
               
                count=2;
                break;
 
                case 2:
               ImageIcon ii=new ImageIcon(getClass().getResource("/test/Death Stranding.jpg"));
                jLabel1.setIcon(ii);
                Thread.sleep(3000);
                ac.jLabelXLeft(0, -840, 20, 7, jLabel1);
                
                count=3;
                break;
                
                
                case 3:
                Thread.sleep(3000);
                ac.jLabelXRight(-840, 0, 20, 7, jLabel1);
               
                count=4;
                break;
                
                 case 4:
               
                Thread.sleep(3000);
                ac.jLabelXLeft(0, -840, 20, 7, jLabel1);
                
                count=5;
                break;
                
                
                case 5:
                Thread.sleep(3000);
               ac.jLabelXRight(-840, 0, 20, 7, jLabel1);
               
                count=0;
                break;
        
        }
        
        
        }
        
        
        }
        catch(Exception e)
        {
        
        
        
        
        }
        
        
        }
        
        }.start();
    
    
    
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        accountDetails = new javax.swing.JMenuItem();
        changePassword = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ViewCart = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ayshi\\OneDrive\\Desktop\\test\\FIFA 20.jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(840, 472));
        jLabel1.setMinimumSize(new java.awt.Dimension(840, 472));
        jLabel1.setPreferredSize(new java.awt.Dimension(840, 472));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/Gears 5.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(840, 472));
        jLabel2.setMinimumSize(new java.awt.Dimension(840, 472));
        jLabel2.setPreferredSize(new java.awt.Dimension(840, 472));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Find");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Game");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Account Settings");

        accountDetails.setText("Account Details");
        accountDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountDetailsActionPerformed(evt);
            }
        });
        jMenu2.add(accountDetails);

        changePassword.setText("Change Password");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });
        jMenu2.add(changePassword);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Cart");

        ViewCart.setText("View Cart");
        ViewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCartActionPerformed(evt);
            }
        });
        jMenu5.add(ViewCart);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("About Us");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("FAQ");
        jMenuBar1.add(jMenu4);

        jMenu6.setText("logout");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(856, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here://Find-->Game
//        FindGame f = new FindGame(user);
//        f.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void accountDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountDetailsActionPerformed
        // TODO add your handling code here:

//        AccountDetails ad = new AccountDetails(user); //passing the user object to the next class
//        ad.setVisible(true);
//        this.setVisible(false);

    }//GEN-LAST:event_accountDetailsActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        // TODO add your handling code here:
//        changePass pass = new changePass(user);
//        pass.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_changePasswordActionPerformed

    private void ViewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCartActionPerformed
        // TODO add your handling code here:
//        CartFrame cf = new CartFrame(user);
//        cf.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_ViewCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(slide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new slide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ViewCart;
    private javax.swing.JMenuItem accountDetails;
    private javax.swing.JMenuItem changePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
